# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 06:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=32)),
                ('verifications_needed', models.PositiveIntegerField(default=3)),
                ('price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('description', models.TextField()),
                ('currency', models.CharField(choices=[('bitcoin', 'BITCOIN'), ('litecoin', 'LITECOIN'), ('etherum', 'ETHEREUM')], max_length=16)),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['is_done'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('image', 'Image')], max_length=16)),
                ('asset', models.TextField()),
                ('is_done', models.BooleanField(default=False)),
                ('labeled_as', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'ordering': ['is_done'],
            },
        ),
    ]
