# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_record_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='answer',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='labeled_as',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
