# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20170916_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['is_done']},
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['is_done']},
        ),
        migrations.AlterField(
            model_name='record',
            name='type',
            field=models.CharField(choices=[('image_classification', 'Image Classification'), ('text_classification', 'Text Classification')], max_length=32),
        ),
    ]
